In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("darkgrid", {"grid.color": ".6"})

In [2]:
sit_1_df = pd.read_csv('processed/biogeme_Situation1.txt', sep='\t', index_col='Id').drop('Unnamed: 245', axis=1)
sit_2_df = pd.read_csv('processed/biogeme_Situation2.txt', sep='\t', index_col='Id').drop('Unnamed: 245', axis=1)
sit_3_df = pd.read_csv('processed/biogeme_Situation3.txt', sep='\t', index_col='Id').drop('Unnamed: 245', axis=1)

In [3]:
sit_1_df['Situation'] = int(1)
sit_1_df['Situation'] = int(2)
sit_1_df['Situation'] = int(3)

In [4]:
#list(sit_1_df.columns)

['Choice',
 'Frequency',
 'Age',
 'Gender',
 'Direct_next_1',
 'Direct_next_2',
 'Direct_next_3',
 'Direct_next_4',
 'Direct_next_5',
 'Direct_next_6',
 'Direct_next_7',
 'Direct_next_8',
 'Direct_next_9',
 'Direct_next_10',
 'Direct_next_11',
 'Direct_next_12',
 'Direct_next_13',
 'Direct_next_14',
 'Direct_next_15',
 'Direct_next_16',
 'Direct_next_17',
 'Direct_next_18',
 'Direct_next_19',
 'Direct_next_20',
 'Direct_next_21',
 'Direct_next_22',
 'Direct_next_23',
 'Direct_next_24',
 'Direct_next_25',
 'Direct_next_26',
 'Direct_next_27',
 'Direct_next_28',
 'Direct_next_29',
 'Direct_next_30',
 'Direct_next_31',
 'Direct_next_32',
 'Direct_next_33',
 'Direct_next_34',
 'Direct_next_35',
 'Direct_next_36',
 'Direct_next_37',
 'Direct_next_38',
 'Direct_next_39',
 'Direct_next_40',
 'People_around_1',
 'People_around_2',
 'People_around_3',
 'People_around_4',
 'People_around_5',
 'People_around_6',
 'People_around_7',
 'People_around_8',
 'People_around_9',
 'People_around_10',
 'People_around_11',
 'People_around_12',
 'People_around_13',
 'People_around_14',
 'People_around_15',
 'People_around_16',
 'People_around_17',
 'People_around_18',
 'People_around_19',
 'People_around_20',
 'People_around_21',
 'People_around_22',
 'People_around_23',
 'People_around_24',
 'People_around_25',
 'People_around_26',
 'People_around_27',
 'People_around_28',
 'People_around_29',
 'People_around_30',
 'People_around_31',
 'People_around_32',
 'People_around_33',
 'People_around_34',
 'People_around_35',
 'People_around_36',
 'People_around_37',
 'People_around_38',
 'People_around_39',
 'People_around_40',
 'Window/wall_1',
 'Window/wall_2',
 'Window/wall_3',
 'Window/wall_4',
 'Window/wall_5',
 'Window/wall_6',
 'Window/wall_7',
 'Window/wall_8',
 'Window/wall_9',
 'Window/wall_10',
 'Window/wall_11',
 'Window/wall_12',
 'Window/wall_13',
 'Window/wall_14',
 'Window/wall_15',
 'Window/wall_16',
 'Window/wall_17',
 'Window/wall_18',
 'Window/wall_19',
 'Window/wall_20',
 'Window/wall_21',
 'Window/wall_22',
 'Window/wall_23',
 'Window/wall_24',
 'Window/wall_25',
 'Window/wall_26',
 'Window/wall_27',
 'Window/wall_28',
 'Window/wall_29',
 'Window/wall_30',
 'Window/wall_31',
 'Window/wall_32',
 'Window/wall_33',
 'Window/wall_34',
 'Window/wall_35',
 'Window/wall_36',
 'Window/wall_37',
 'Window/wall_38',
 'Window/wall_39',
 'Window/wall_40',
 'Distance_to_exit_1',
 'Distance_to_exit_2',
 'Distance_to_exit_3',
 'Distance_to_exit_4',
 'Distance_to_exit_5',
 'Distance_to_exit_6',
 'Distance_to_exit_7',
 'Distance_to_exit_8',
 'Distance_to_exit_9',
 'Distance_to_exit_10',
 'Distance_to_exit_11',
 'Distance_to_exit_12',
 'Distance_to_exit_13',
 'Distance_to_exit_14',
 'Distance_to_exit_15',
 'Distance_to_exit_16',
 'Distance_to_exit_17',
 'Distance_to_exit_18',
 'Distance_to_exit_19',
 'Distance_to_exit_20',
 'Distance_to_exit_21',
 'Distance_to_exit_22',
 'Distance_to_exit_23',
 'Distance_to_exit_24',
 'Distance_to_exit_25',
 'Distance_to_exit_26',
 'Distance_to_exit_27',
 'Distance_to_exit_28',
 'Distance_to_exit_29',
 'Distance_to_exit_30',
 'Distance_to_exit_31',
 'Distance_to_exit_32',
 'Distance_to_exit_33',
 'Distance_to_exit_34',
 'Distance_to_exit_35',
 'Distance_to_exit_36',
 'Distance_to_exit_37',
 'Distance_to_exit_38',
 'Distance_to_exit_39',
 'Distance_to_exit_40',
 'two_or4_seat_1',
 'two_or4_seat_2',
 'two_or4_seat_3',
 'two_or4_seat_4',
 'two_or4_seat_5',
 'two_or4_seat_6',
 'two_or4_seat_7',
 'two_or4_seat_8',
 'two_or4_seat_9',
 'two_or4_seat_10',
 'two_or4_seat_11',
 'two_or4_seat_12',
 'two_or4_seat_13',
 'two_or4_seat_14',
 'two_or4_seat_15',
 'two_or4_seat_16',
 'two_or4_seat_17',
 'two_or4_seat_18',
 'two_or4_seat_19',
 'two_or4_seat_20',
 'two_or4_seat_21',
 'two_or4_seat_22',
 'two_or4_seat_23',
 'two_or4_seat_24',
 'two_or4_seat_25',
 'two_or4_seat_26',
 'two_or4_seat_27',
 'two_or4_seat_28',
 'two_or4_seat_29',
 'two_or4_seat_30',
 'two_or4_seat_31',
 'two_or4_seat_32',
 'two_or4_seat_33',
 'two_or4_seat_34',
 'two_or4_seat_35',
 'two_or4_seat_36',
 'two_or4_seat_37',
 'two_or4_seat_38',
 'two_or4_seat_39',
 'two_or4_seat_40',
 'SEATAV_1',
 'SEATAV_2',
 'SEATAV_3',
 'SEATAV_4',
 'SEATAV_5',
 'SEATAV_6',
 'SEATAV_7',
 'SEATAV_8',
 'SEATAV_9',
 'SEATAV_10',
 'SEATAV_11',
 'SEATAV_12',
 'SEATAV_13',
 'SEATAV_14',
 'SEATAV_15',
 'SEATAV_16',
 'SEATAV_17',
 'SEATAV_18',
 'SEATAV_19',
 'SEATAV_20',
 'SEATAV_21',
 'SEATAV_22',
 'SEATAV_23',
 'SEATAV_24',
 'SEATAV_25',
 'SEATAV_26',
 'SEATAV_27',
 'SEATAV_28',
 'SEATAV_29',
 'SEATAV_30',
 'SEATAV_31',
 'SEATAV_32',
 'SEATAV_33',
 'SEATAV_34',
 'SEATAV_35',
 'SEATAV_36',
 'SEATAV_37',
 'SEATAV_38',
 'SEATAV_39',
 'SEATAV_40',
 'Situation']

In [5]:
# Rename columns

rename_dict = {}

for i in range(1,41):
    rename_dict[f'Window/wall_{i}'] = f'Windowwall_{i}'

sit_1_df.rename(columns=rename_dict, inplace=True)
sit_2_df.rename(columns=rename_dict, inplace=True)
sit_3_df.rename(columns=rename_dict, inplace=True)

In [6]:
dfs = [sit_1_df, sit_2_df, sit_3_df]
merged_df = pd.concat(dfs)

In [7]:
merged_df

,Choice,Frequency,Age,Gender,Direct_next_1,Direct_next_2,Direct_next_3,Direct_next_4,Direct_next_5,Direct_next_6,...,SEATAV_32,SEATAV_33,SEATAV_34,SEATAV_35,SEATAV_36,SEATAV_37,SEATAV_38,SEATAV_39,SEATAV_40,Situation
Id,,,,,,,,,,,,,,,,,,,,,
1,8,2,2,1,1,99999,0,0,0,0,...,1,1,1,1,1,1,1,0,0,3.0
2,32,2,3,2,1,99999,0,0,0,0,...,1,1,1,1,1,1,1,0,0,3.0
3,19,3,2,2,1,99999,0,0,0,0,...,1,1,1,1,1,1,1,0,0,3.0
4,32,2,1,1,1,99999,0,0,0,0,...,1,1,1,1,1,1,1,0,0,3.0
5,10,1,2,1,1,99999,0,0,0,0,...,1,1,1,1,1,1,1,0,0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,15,2,1,2,1,99999,99999,1,99999,1,...,0,0,1,0,0,1,1,1,0,NaN
510,12,2,3,1,1,99999,99999,1,99999,1,...,0,0,1,0,0,1,1,1,0,NaN
511,12,3,2,2,1,99999,99999,1,99999,1,...,0,0,1,0,0,1,1,1,0,NaN
512,11,2,2,1,1,99999,99999,1,99999,1,...,0,0,1,0,0,1,1,1,0,NaN
513,12,3,1,2,1,99999,99999,1,99999,1,...,0,0,1,0,0,1,1,1,0,NaN

In [8]:
sit_1_df.to_csv('processed/biogeme_Situation1.dat', sep='\t')
sit_2_df.to_csv('processed/biogeme_Situation2.dat', sep='\t')
sit_3_df.to_csv('processed/biogeme_Situation3.dat', sep='\t')
merged_df.to_csv('processed/biogeme_all_situations.dat', sep='\t')